from __future__ import annotations


BRAND_SEGMENT_COLOR_UPDATES = {
    "apple": {
        "Products": "#111827",
        "iPhone": "#111827",
        "Services": "#2563EB",
        "Mac": "#0EA5E9",
        "iPad": "#14B8A6",
        "Wearables, Home and Accessories": "#94A3B8",
    },
    "microsoft": {
        "Productivity and Business Processes": "#2563EB",
        "Intelligent Cloud": "#14B8A6",
        "More Personal Computing": "#F59E0B",
        "Product revenue": "#2563EB",
        "Service and other revenue": "#14B8A6",
    },
    "alphabet": {
        "Google Services": "#2563EB",
        "Google Search & other": "#2563EB",
        "YouTube ads": "#DC2626",
        "Google Network": "#F59E0B",
        "Google subscriptions, platforms, and devices": "#0F9D58",
        "Google Cloud": "#1A73E8",
        "Other Bets": "#64748B",
    },
    "amazon": {
        "North America": "#111827",
        "International": "#F59E0B",
        "AWS": "#2563EB",
        "Online stores": "#111827",
        "Third-party seller services": "#F59E0B",
        "Advertising services": "#2563EB",
        "Subscription services": "#0EA5E9",
        "Physical stores": "#94A3B8",
        "Other": "#CBD5E1",
    },
    "meta": {
        "Family of Apps": "#0866FF",
        "Reality Labs": "#16A34A",
    },
    "tsla": {
        "Automotive": "#DC2626",
        "Energy Generation and Storage": "#10B981",
        "Services and Other": "#64748B",
    },
}


OFFICIAL_MAG7_FIXTURES = {
    ("apple", "2025Q4"): {
        "fiscal_label": "Q1 FY2026",
        "release_date": "2026-01-29",
        "period_end": "2025-12-27",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "sec_filing", "call_summary"],
        "headline": "iPhone 假日季需求、Services 纪录收入与安装基数扩张共振，Apple 在 Q1 FY2026 交出收入、利润与现金流同步走强的季度。",
        "takeaways": [
            "收入 1437.6 亿美元，同比增长 15.7%；iPhone 与 Services 收入分别约为 852.7 / 300.1 亿美元，假日季仍由硬件与服务双引擎驱动。",
            "10-Q 显示 Products / Services 收入分别为 1137.4 / 300.1 亿美元；按官方成本表推算，两者毛利率约为 40.7% / 76.5%，Services 继续抬升盈利质量。",
            "经营利润 528.4 亿美元、净利润 421.0 亿美元、EPS 2.84；经营现金流 539.5 亿美元，利润兑现与现金创造同步走强。",
            "公司未给出数值收入指引，但管理层继续强调活跃设备安装基数创新高，Services 与 Apple Intelligence rollout 仍是主线。",
        ],
        "latest_kpis": {
            "revenue_bn": 143.756,
            "revenue_yoy_pct": 15.7,
            "revenue_qoq_pct": 40.3,
            "gaap_gross_margin_pct": 48.2,
            "non_gaap_gross_margin_pct": 48.2,
            "operating_income_bn": 52.839,
            "net_income_bn": 42.097,
            "net_income_yoy_pct": 15.9,
            "operating_cash_flow_bn": 53.948,
            "free_cash_flow_bn": None,
            "gaap_eps": 2.84,
            "non_gaap_eps": 2.84,
        },
        "guidance": {
            "mode": "official_context",
            "current_label": "本季收入",
            "comparison_label": "近四季季度均值",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "公司没有给出数值 top-line 指引，本页用经营基线承接官方管理层语境；重点仍在 installed base、Services 韧性与 AI 功能带来的换机预期。",
        },
        "current_segments": [
            {"name": "iPhone", "value_bn": 85.267, "yoy_pct": 23.3},
            {"name": "Services", "value_bn": 30.013, "yoy_pct": 4.9},
            {"name": "Wearables, Home and Accessories", "value_bn": 11.747, "yoy_pct": 0.0},
            {"name": "Mac", "value_bn": 8.987, "yoy_pct": 15.5},
            {"name": "iPad", "value_bn": 8.088, "yoy_pct": 15.2},
        ],
        "income_statement": {
            "subtitle": "利润表页改用 Apple 官方 Products / Services 拆分，并保留研发、销管与税项的可读桥接。",
            "sources": [
                {"name": "Products", "value_bn": 113.743, "yoy_pct": 18.9, "margin_pct": 40.7},
                {"name": "Services", "value_bn": 30.013, "yoy_pct": 4.9, "margin_pct": 76.5},
            ],
            "opex_breakdown": [
                {"name": "Research and development", "value_bn": 8.861, "pct_of_revenue": 6.2, "color": "#E11D48"},
                {"name": "Selling, general and administrative", "value_bn": 7.531, "pct_of_revenue": 5.2, "color": "#F43F5E"},
            ],
            "below_operating_items": [
                {"name": "Taxes net of other income", "value_bn": 10.742, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "iPhone 仍是主引擎", "value": "$85.3B | +23.3% YoY", "note": "单品类仍贡献了接近六成收入。", "color": "#111827"},
                {"title": "Services 高毛利", "value": "$30.0B | 76.5% margin", "note": "高毛利业务继续抬升整体利润质量。", "color": "#2563EB"},
                {"title": "现金流兑现", "value": "$53.9B OCF", "note": "利润增长没有停留在会计口径。", "color": "#0EA5E9"},
            ],
        },
        "management_themes": [
            {"label": "iPhone 周期与高端机型 mix", "score": 90, "note": "假日季 iPhone 需求仍是体量最大、对利润最敏感的驱动。"},
            {"label": "Services 继续抬高盈利质量", "score": 88, "note": "Services 收入与毛利继续改善整体利润结构。"},
            {"label": "活跃安装基数创新高", "score": 79, "note": "安装基数扩大意味着后续订阅、支付与生态变现更有支撑。"},
            {"label": "Apple Intelligence rollout", "score": 72, "note": "AI 功能扩展更像中期换机催化，而非单季收入跳变。"},
        ],
        "qna_themes": [
            {"label": "中国市场与区域节奏", "score": 76, "note": "市场更关注中国竞争格局与区域 mix 对硬件收入的影响。"},
            {"label": "Services 增长可持续性", "score": 72, "note": "高毛利服务业务能否继续快于硬件增长，是利润弹性的关键。"},
            {"label": "毛利率与产品 mix", "score": 68, "note": "硬件新品节奏、促销强度与服务占比共同影响毛利率。"},
            {"label": "AI 功能带动换机的时点", "score": 63, "note": "投资人更关心 AI 功能能否转化为更实质的升级周期。"},
        ],
        "risks": [
            {"label": "iPhone 周期回落", "score": 64, "note": "硬件升级若提前透支，后续季度同比与毛利率弹性会同步放缓。"},
            {"label": "中国竞争与区域 mix", "score": 58, "note": "区域性需求与竞争压力会先反映在 iPhone 收入结构上。"},
            {"label": "AI 功能兑现慢于预期", "score": 47, "note": "若 AI 体验对换机拉动有限，估值叙事会更依赖 Services。"},
        ],
        "catalysts": [
            {"label": "Services 继续超预期", "score": 89, "note": "更高占比的高毛利收入会持续改善利润结构。"},
            {"label": "AI 带动换机升级", "score": 73, "note": "若 Apple Intelligence 带来更清晰的升级理由，硬件周期可获再强化。"},
            {"label": "资本回报延续", "score": 60, "note": "高现金流与股东回报仍是估值韧性的底层支撑。"},
        ],
        "evidence_cards": [
            {
                "title": "总量与利润",
                "text": "官方材料显示季度净销售额 1437.6 亿美元、经营利润 528.4 亿美元、净利润 421.0 亿美元、EPS 2.84。",
                "source_label": "Apple earnings release",
            },
            {
                "title": "结构拆分",
                "text": "10-Q 披露 iPhone 收入约 852.7 亿美元、Services 收入 300.1 亿美元；Products / Services 毛利率约为 40.7% / 76.5%。",
                "source_label": "Apple Form 10-Q",
            },
            {
                "title": "现金创造",
                "text": "官方口径显示经营现金流达到 539.5 亿美元，说明利润兑现没有停留在会计口径。",
                "source_label": "Apple earnings release",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Tim Cook",
                "quote": "活跃设备安装基数再次创下历史新高。",
                "analysis": "这意味着后续订阅、支付和设备内 AI 功能扩张仍有更厚的用户底盘支撑。",
                "source_label": "Apple earnings release",
            },
            {
                "speaker": "Management",
                "quote": "Services 在假日季继续刷新收入纪录。",
                "analysis": "Services 的高毛利属性继续抬升整体利润结构，也让 Apple Intelligence 的长期变现更有抓手。",
                "source_label": "Apple earnings release",
            },
        ],
        "coverage_notes": [
            "当季结果、产品结构与现金流锚点已切换到 Apple 官方新闻稿和 10-Q 口径。",
            "利润桥图页改用 Products / Services 官方收入结构，避免与圆环页的产品线拆分重复。",
            "公司没有给出数值收入指引，因此指引页以官方管理层语境叠加经营基线展示。",
            "历史利润趋势页以经营利润率为主，因为长期结构化利润序列与官方净利润披露并不完全同口径。",
        ],
        "sources": [
            {
                "label": "Apple Q1 FY2026 earnings release",
                "url": "https://www.apple.com/newsroom/2026/01/apple-reports-first-quarter-results/",
                "kind": "official_release",
                "date": "2026-01-29",
            },
            {
                "label": "Apple Form 10-Q",
                "url": "https://www.sec.gov/Archives/edgar/data/0000320193/000032019326000006/aapl-20251227.htm",
                "kind": "sec_filing",
                "date": "2026-01-30",
            },
        ],
    },
    ("microsoft", "2025Q4"): {
        "fiscal_label": "FY2026 Q2",
        "release_date": "2026-01-28",
        "period_end": "2025-12-31",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "call_summary"],
        "headline": "Azure、企业软件与 AI 供给扩张继续共振，Microsoft FY2026 Q2 的收入、经营利润与净利润都维持高质量增长。",
        "takeaways": [
            "收入 813 亿美元，同比增长 12.3%；Productivity and Business Processes / Intelligent Cloud / More Personal Computing 收入分别为 342 / 318 / 154 亿美元。",
            "Azure 及其他云服务收入增长 31%，按固定汇率增长 32%，AI 需求和供给扩容仍是电话会核心。",
            "经营利润 383 亿美元、净利润 272 亿美元、EPS 3.65；10-Q 同时披露 Product revenue 335 亿美元、Service and other revenue 477 亿美元。",
            "公司未给 consolidated top-line 指引，但管理层继续强调云与 AI 需求强劲，供给扩容仍是关键变量。",
        ],
        "latest_kpis": {
            "revenue_bn": 81.273,
            "revenue_yoy_pct": 12.3,
            "revenue_qoq_pct": 9.1,
            "gaap_gross_margin_pct": 69.4,
            "non_gaap_gross_margin_pct": 69.4,
            "operating_income_bn": 38.275,
            "net_income_bn": 27.233,
            "net_income_yoy_pct": 13.0,
            "operating_cash_flow_bn": None,
            "free_cash_flow_bn": None,
            "gaap_eps": 3.65,
            "non_gaap_eps": 3.65,
        },
        "guidance": {
            "mode": "official_context",
            "current_label": "本季收入",
            "comparison_label": "近四季季度均值",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "公司没有给出 consolidated revenue 数值指引，但电话会持续强调 Azure / AI 需求与容量扩张，本页用经营基线承接官方表述。",
        },
        "current_segments": [
            {"name": "Productivity and Business Processes", "value_bn": 34.157, "yoy_pct": 16.0},
            {"name": "Intelligent Cloud", "value_bn": 31.758, "yoy_pct": 18.7},
            {"name": "More Personal Computing", "value_bn": 15.358, "yoy_pct": 4.8},
        ],
        "income_statement": {
            "subtitle": "利润表页以业务集团桥接收入，并向下串联 Microsoft 官方成本与经营费用科目。",
            "sources": [
                {"name": "Product revenue", "value_bn": 33.535, "yoy_pct": 5.0},
                {"name": "Service and other revenue", "value_bn": 47.738, "yoy_pct": 30.4},
            ],
            "opex_breakdown": [
                {"name": "Research and development", "value_bn": 9.233, "pct_of_revenue": 12.1, "color": "#E11D48"},
                {"name": "Sales and marketing", "value_bn": 7.078, "pct_of_revenue": 9.3, "color": "#F43F5E"},
                {"name": "General and administrative", "value_bn": 1.804, "pct_of_revenue": 2.4, "color": "#FB7185"},
            ],
            "below_operating_items": [
                {"name": "Taxes net of other", "value_bn": 11.042, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "Microsoft Cloud 创新高", "value": "> $50B quarterly revenue", "note": "官方明确这是首次单季突破 500 亿美元。", "color": "#0078D4"},
                {"title": "Azure 继续高增", "value": "+31% YoY", "note": "AI 供需两侧都在继续推高云业务增速。", "color": "#2563EB"},
                {"title": "服务收入占优", "value": "$47.7B service mix", "note": "高质量经常性收入继续支撑利润韧性。", "color": "#0EA5E9"},
            ],
        },
        "management_themes": [
            {"label": "Azure 与 AI 需求延续", "score": 92, "note": "Azure 及其他云服务同比增长 32%，AI 需求仍是增速核心。"},
            {"label": "Copilot 商业化渗透", "score": 80, "note": "企业软件平台正在把 AI 功能变成更可持续的 ARPU 提升。"},
            {"label": "供给扩容与 capex 节奏", "score": 77, "note": "需求强劲并不稀缺，真正稀缺的是可交付的算力与数据中心容量。"},
            {"label": "云与软件 mix 的利润韧性", "score": 73, "note": "高毛利的软件平台继续帮助公司在重投入周期里守住利润率。"},
        ],
        "qna_themes": [
            {"label": "Azure 容量瓶颈与兑现", "score": 81, "note": "市场继续追问供给何时能更充分匹配 AI 工作负载需求。"},
            {"label": "AI 服务货币化节奏", "score": 74, "note": "Copilot 与 AI infrastructure 的商业化速度决定收入持续性。"},
            {"label": "数据中心资本开支", "score": 71, "note": "投资人会把 capex 强度与后续毛利率路径一起看。"},
            {"label": "企业 IT 预算健康度", "score": 62, "note": "非 AI 工作负载的稳定度决定增长能否更均衡。"},
        ],
        "risks": [
            {"label": "AI capex 挤压利润率", "score": 58, "note": "基础设施投入若持续快于变现，会压缩短期利润率。"},
            {"label": "Azure 供给瓶颈", "score": 55, "note": "交付能力落后于需求时，收入确认节奏会被动后移。"},
            {"label": "企业预算收紧", "score": 44, "note": "更广泛的软件席位或云工作负载若放缓，会拖累增长质量。"},
        ],
        "catalysts": [
            {"label": "Azure 再加速", "score": 90, "note": "若 AI 容量释放更快，云收入与市场情绪都会同步受益。"},
            {"label": "Copilot attach rate 提升", "score": 72, "note": "AI 功能渗透越深，企业软件平台的变现深度越强。"},
            {"label": "利润率韧性超预期", "score": 68, "note": "在 capex 高位下仍能守住利润率，是估值扩张的重要锚。"},
        ],
        "evidence_cards": [
            {
                "title": "收入与利润",
                "text": "官方新闻稿披露 FY2026 Q2 收入 813 亿美元、经营利润 383 亿美元、净利润 272 亿美元、EPS 3.65。",
                "source_label": "Microsoft earnings release",
            },
            {
                "title": "云业务动能",
                "text": "Azure 及其他云服务收入增长 31%，按固定汇率增长 32%，AI 需求仍在高位。",
                "source_label": "Microsoft earnings release",
            },
            {
                "title": "分部结构",
                "text": "10-Q 披露 Productivity and Business Processes / Intelligent Cloud / More Personal Computing 收入分别为 342 / 318 / 154 亿美元。",
                "source_label": "Microsoft earnings release",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Satya Nadella",
                "quote": "Cloud and AI are the essential inputs for every business.",
                "analysis": "管理层继续把 Azure、数据平台和 Copilot 放在同一轮企业 IT 升级的核心位置。",
                "source_label": "Microsoft earnings release",
            },
            {
                "speaker": "Management",
                "quote": "Microsoft Cloud 首次单季收入突破 500 亿美元。",
                "analysis": "这不仅是云规模的新台阶，也说明 AI 工作负载正在更深地嵌入公司收入结构。",
                "source_label": "Microsoft earnings release",
            },
        ],
        "coverage_notes": [
            "当季结果与分部拆分已切换到 Microsoft 官方新闻稿口径。",
            "利润桥图页以三大业务集团承接收入，再向下连接 Microsoft 官方成本与经营费用科目。",
            "公司没有给出 consolidated revenue 数值指引，因此指引页展示官方管理层语境与经营基线的并读结果。",
        ],
        "sources": [
            {
                "label": "Microsoft FY2026 Q2 press release",
                "url": "https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q2/press-release-webcast",
                "kind": "official_release",
                "date": "2026-01-28",
            },
            {
                "label": "Microsoft Form 10-Q",
                "url": "https://www.sec.gov/Archives/edgar/data/789019/000119312526027207/msft-20251231.htm",
                "kind": "sec_filing",
                "date": "2026-01-28",
            },
        ],
    },
    ("alphabet", "2025Q4"): {
        "fiscal_label": "Q4 2025",
        "release_date": "2026-02-03",
        "period_end": "2025-12-31",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "call_summary"],
        "headline": "Search 韧性、YouTube 与 Cloud 共振放大了 AI 期的经营杠杆，Alphabet Q4 2025 的收入、经营利润与净利润都明显提速。",
        "takeaways": [
            "收入 1138.3 亿美元，同比增长 18.0%；经营利润 359.3 亿美元、净利润 344.6 亿美元、EPS 2.84。",
            "Google Services / Google Cloud / Other Bets 收入分别为 955.5 / 176.6 / 4.0 亿美元，Cloud 同比增长 30%，仍是最强第二曲线。",
            "利润桥图页改用 Search、YouTube、Network、订阅硬件与 Cloud 的官方收入科目，AI 投入下经营杠杆仍在继续释放。",
            "公司没有给出数值收入指引，但管理层继续强调 Search 韧性、Cloud/AI 需求与更高资本开支投入。",
        ],
        "latest_kpis": {
            "revenue_bn": 113.828,
            "revenue_yoy_pct": 18.0,
            "revenue_qoq_pct": 11.2,
            "gaap_gross_margin_pct": 59.8,
            "non_gaap_gross_margin_pct": 59.8,
            "operating_income_bn": 35.934,
            "net_income_bn": 34.455,
            "net_income_yoy_pct": 29.8,
            "operating_cash_flow_bn": None,
            "free_cash_flow_bn": None,
            "gaap_eps": 2.84,
            "non_gaap_eps": 2.84,
        },
        "guidance": {
            "mode": "official_context",
            "current_label": "本季收入",
            "comparison_label": "近四季季度均值",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "公司没有给出数值收入指引，本页用经营基线承接官方展望；真正的核心变量仍是 Search 广告韧性、Cloud 利润兑现与 AI capex 的回报路径。",
        },
        "current_segments": [
            {"name": "Google Services", "value_bn": 95.545, "yoy_pct": 10.0},
            {"name": "Google Cloud", "value_bn": 17.664, "yoy_pct": 30.0},
            {"name": "Other Bets", "value_bn": 0.400, "yoy_pct": 3.1},
        ],
        "income_statement": {
            "subtitle": "利润表页改用 Alphabet 官方收入科目与费用科目，既保留 Search / YouTube / Cloud 细分，也能和经营利润读在一起。",
            "sources": [
                {"name": "Google Search & other", "value_bn": 63.102, "yoy_pct": 16.8},
                {"name": "YouTube ads", "value_bn": 11.427, "yoy_pct": 9.1},
                {"name": "Google Network", "value_bn": 7.763, "yoy_pct": -3.0},
                {"name": "Google subscriptions, platforms, and devices", "value_bn": 13.552, "yoy_pct": 12.1},
                {"name": "Google Cloud", "value_bn": 17.664, "yoy_pct": 35.4},
                {"name": "Other Bets", "value_bn": 0.400, "yoy_pct": 3.1},
            ],
            "opex_breakdown": [
                {"name": "Research and development", "value_bn": 16.428, "pct_of_revenue": 14.4, "color": "#E11D48"},
                {"name": "Sales and marketing", "value_bn": 8.606, "pct_of_revenue": 7.6, "color": "#F43F5E"},
                {"name": "General and administrative", "value_bn": 3.529, "pct_of_revenue": 3.1, "color": "#FB7185"},
                {"name": "Other operating items", "value_bn": 3.548, "pct_of_revenue": 3.1, "color": "#FDA4AF"},
            ],
            "below_operating_items": [
                {"name": "Taxes net of other income", "value_bn": 1.479, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "Search 仍是底盘", "value": "$63.1B | +16.8% YoY", "note": "搜索广告仍然贡献了最厚的现金流与利润底盘。", "color": "#2563EB"},
                {"title": "Cloud 加速变现", "value": "$17.7B | +35.4% YoY", "note": "Cloud 增速显著快于集团收入，第二曲线更扎实。", "color": "#1A73E8"},
                {"title": "经营杠杆延续", "value": "$35.9B operating income", "note": "在更高 AI 投入下，利润兑现仍在继续上修。", "color": "#0F9D58"},
            ],
        },
        "management_themes": [
            {"label": "Search 广告韧性", "score": 90, "note": "Search 仍是现金流最强底盘，AI 摘要并未削弱广告基本盘。"},
            {"label": "Google Cloud 扩张与利润率", "score": 86, "note": "Cloud 不再只是增长故事，也在变成更重要的利润故事。"},
            {"label": "AI capex 与基础设施", "score": 79, "note": "更高资本开支是抢 AI 需求与守住产品力的必要投入。"},
            {"label": "YouTube 与订阅生态", "score": 68, "note": "YouTube、订阅和平台业务提供了更分散的增长来源。"},
        ],
        "qna_themes": [
            {"label": "AI Overviews 对搜索变现的影响", "score": 77, "note": "市场持续关注 AI 产品形态是否会改变搜索点击与广告单价。"},
            {"label": "Cloud backlog 与供给", "score": 73, "note": "Cloud 的持续加速取决于需求兑现与交付能力同步推进。"},
            {"label": "资本开支强度", "score": 70, "note": "投资人希望看到更高 capex 最终如何反馈到收入与利润率。"},
            {"label": "YouTube 与订阅增长", "score": 61, "note": "非 Search 业务能否持续抬升占比，决定结构扩散程度。"},
        ],
        "risks": [
            {"label": "AI 投入回报期拉长", "score": 57, "note": "若 capex 提升快于收入兑现，利润率会阶段性承压。"},
            {"label": "广告预算波动", "score": 50, "note": "宏观与垂类广告需求变化仍会先反映在 Search 与 YouTube。"},
            {"label": "监管与产品形态变化", "score": 45, "note": "搜索与平台生态的监管压力仍会影响长期估值。"},
        ],
        "catalysts": [
            {"label": "Cloud 再加速", "score": 84, "note": "Cloud 增长和利润率同步改善会显著强化第二曲线逻辑。"},
            {"label": "Search AI 体验商业化", "score": 75, "note": "AI 产品若进一步提升变现效率，Search 估值中枢有望再抬升。"},
            {"label": "利润率维持高位", "score": 70, "note": "在更高 capex 下仍守住利润率，会强化市场对经营质量的信心。"},
        ],
        "evidence_cards": [
            {
                "title": "总收入与利润",
                "text": "官方 earnings release 披露 Q4 2025 收入 1138.3 亿美元、经营利润 359.3 亿美元、净利润 344.6 亿美元、EPS 2.84。",
                "source_label": "Alphabet earnings release",
            },
            {
                "title": "核心业务结构",
                "text": "Google Services / Google Cloud / Other Bets 收入分别为 955.5 / 176.6 / 4.0 亿美元；其中 Cloud 继续维持 30% 增长。",
                "source_label": "Alphabet earnings release",
            },
            {
                "title": "AI 投入主线",
                "text": "官方 PDF 披露 Q4 cost of revenues、R&D 与销售费用分别约为 449 / 164 / 86 亿美元，AI 投入仍在继续抬高费用基座。",
                "source_label": "Alphabet earnings release",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Sundar Pichai",
                "quote": "Our differentiated full stack approach to AI continues to drive growth.",
                "analysis": "AI 已不只是成本项，而是在 Search、YouTube 与 Cloud 上同步转化为收入与利润项。",
                "source_label": "Alphabet earnings release",
            },
            {
                "speaker": "Management",
                "quote": "Search、YouTube 与 Cloud 同时维持强劲增长。",
                "analysis": "这意味着 Alphabet 当前并不是单一依赖 Search 的故事，而是多业务共同承接 AI 需求与广告韧性。",
                "source_label": "Alphabet earnings release",
            },
        ],
        "coverage_notes": [
            "当季结果与主要收入结构已切换到 Alphabet 官方 earnings release 口径。",
            "圆环页展示 Google Services / Cloud / Other Bets，利润桥图页则进一步下钻到 Search、YouTube 与订阅硬件科目。",
            "公司没有给出数值收入指引，因此指引页以官方管理层语境叠加经营基线展示。",
        ],
        "sources": [
            {
                "label": "Alphabet Q4 2025 earnings release",
                "url": "https://abc.xyz/investor/news/news-details/2026/Alphabet-Announces-Fourth-Quarter-2025-and-Fiscal-Year-Results-2026-KEvZIMKBLS/default.aspx",
                "kind": "official_release",
                "date": "2026-02-03",
            },
            {
                "label": "Alphabet 2025 Q4 earnings call",
                "url": "https://abc.xyz/investor/events/event-details/2026/2025-Q4-Earnings-Call-2026-Dr_C033hS6/default.aspx",
                "kind": "call_summary",
                "date": "2026-02-03",
            },
        ],
    },
    ("amazon", "2025Q4"): {
        "fiscal_label": "Q4 2025",
        "release_date": "2026-02-05",
        "period_end": "2025-12-31",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "call_summary"],
        "headline": "AWS、广告和平台服务继续抬高利润池，Amazon Q4 2025 在节日季交出更强的收入规模与经营利润。",
        "takeaways": [
            "收入 2133.9 亿美元，同比增长 14.0%；North America / International / AWS 收入分别约为 1271 / 507 / 356 亿美元。",
            "经营利润 250 亿美元、净利润 200 亿美元、EPS 1.86；AWS 继续充当利润中枢，广告与平台服务也在抬升收入质量。",
            "按官方收入类别，Online stores / Third-party seller services / AWS / Advertising services 分别为 829.9 / 528.2 / 355.8 / 213.2 亿美元，业务结构比过去更均衡。",
            "Q1 2026 收入指引区间为 1510 亿至 1555 亿美元，对应同比增长 5% 至 8%。",
        ],
        "latest_kpis": {
            "revenue_bn": 213.386,
            "revenue_yoy_pct": 14.0,
            "revenue_qoq_pct": 18.4,
            "gaap_gross_margin_pct": 48.5,
            "non_gaap_gross_margin_pct": 48.5,
            "operating_income_bn": 25.000,
            "net_income_bn": 20.000,
            "net_income_yoy_pct": 0.0,
            "operating_cash_flow_bn": None,
            "free_cash_flow_bn": None,
            "gaap_eps": 1.86,
            "non_gaap_eps": 1.86,
        },
        "guidance": {
            "mode": "official",
            "revenue_bn": 153.25,
            "comparison_revenue_bn": 213.386,
            "gaap_gross_margin_pct": None,
            "comparison_margin_pct": 48.5,
            "current_label": "本季收入",
            "comparison_label": "下一季收入指引中枢",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "官方给出 Q1 2026 收入指引 1510 亿至 1555 亿美元；利润率未给数值指引，因此图中利润率面板采用历史中枢作为参考锚。",
        },
        "current_segments": [
            {"name": "North America", "value_bn": 127.126},
            {"name": "International", "value_bn": 50.698},
            {"name": "AWS", "value_bn": 35.579, "yoy_pct": 17.0},
        ],
        "income_statement": {
            "subtitle": "利润表页改用 Amazon 官方收入类别与费用科目，让零售、平台服务和 AWS 的利润桥一眼可读。",
            "sources": [
                {"name": "Online stores", "value_bn": 82.988},
                {"name": "Third-party seller services", "value_bn": 52.816},
                {"name": "AWS", "value_bn": 35.579, "yoy_pct": 17.0},
                {"name": "Advertising services", "value_bn": 21.317},
                {"name": "Subscription services", "value_bn": 13.122},
                {"name": "Physical stores", "value_bn": 5.855},
                {"name": "Other", "value_bn": 1.709},
            ],
            "opex_breakdown": [
                {"name": "Fulfillment", "value_bn": 31.895, "pct_of_revenue": 14.9, "color": "#E11D48"},
                {"name": "Technology and infrastructure", "value_bn": 30.678, "pct_of_revenue": 14.4, "color": "#F43F5E"},
                {"name": "Marketing", "value_bn": 6.218, "pct_of_revenue": 2.9, "color": "#FB7185"},
                {"name": "General and administrative", "value_bn": 1.985, "pct_of_revenue": 0.9, "color": "#FDA4AF"},
                {"name": "Other operating items", "value_bn": 7.646, "pct_of_revenue": 3.6, "color": "#BE123C"},
            ],
            "below_operating_items": [
                {"name": "Tax & other", "value_bn": 5.000, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "AWS 仍是利润中枢", "value": "$35.6B | +17% YoY", "note": "云业务仍是最关键的利润与估值锚。", "color": "#2563EB"},
                {"title": "平台服务继续扩张", "value": "$87.3B 3P+Ads+Subs", "note": "高质量平台型收入已成为零售之外的第二引擎。", "color": "#F59E0B"},
                {"title": "下季回归季节性", "value": "$151.0B-$155.5B guide", "note": "节后季节性回落，但管理层仍维持 5%-8% 同比增长预期。", "color": "#111827"},
            ],
        },
        "management_themes": [
            {"label": "AWS 与 AI 基础设施", "score": 90, "note": "AWS 增长、AI 需求与相关 capex 仍是估值核心。"},
            {"label": "零售效率继续兑现", "score": 84, "note": "履约与成本优化让 North America 与 International 利润率继续改善。"},
            {"label": "广告与第三方平台", "score": 73, "note": "高毛利广告与平台服务继续增强整体收入质量。"},
            {"label": "区域盈利能力更均衡", "score": 67, "note": "International 端的改善让利润结构不再过度依赖 AWS。"},
        ],
        "qna_themes": [
            {"label": "AWS 供给与需求匹配", "score": 80, "note": "市场继续追问 AI 相关容量释放能否支撑后续增速。"},
            {"label": "零售利润率持续性", "score": 74, "note": "投资人关心零售效率改善是周期性还是结构性。"},
            {"label": "资本开支与自由现金流", "score": 70, "note": "AI 基建投资提速会影响现金流节奏与利润率预期。"},
            {"label": "广告增长质量", "score": 61, "note": "广告业务继续扩张能否保持高利润率，是估值的重要支撑。"},
        ],
        "risks": [
            {"label": "高 capex 压力", "score": 61, "note": "AI 与云基础设施投入加速，可能拖累短期现金流表现。"},
            {"label": "零售需求与汇率波动", "score": 49, "note": "消费需求与汇率变化会先影响零售收入和区域利润。"},
            {"label": "AWS 竞争加剧", "score": 46, "note": "若云与 AI 基础设施竞争更激烈，增速与利润率都会受压。"},
        ],
        "catalysts": [
            {"label": "AWS 再加速", "score": 88, "note": "若 AI 相关供给更快释放，AWS 增速上修空间仍在。"},
            {"label": "零售利润率继续抬升", "score": 76, "note": "北美与国际零售持续提效会强化整体盈利中枢。"},
            {"label": "广告飞轮更强", "score": 67, "note": "广告与平台服务扩张会进一步改善收入结构。"},
        ],
        "evidence_cards": [
            {
                "title": "收入与 EPS",
                "text": "官方披露 Q4 2025 收入 2133.9 亿美元、经营利润 250 亿美元、净利润 200 亿美元、EPS 1.86。",
                "source_label": "Amazon earnings release",
            },
            {
                "title": "分部结构",
                "text": "North America / International / AWS 收入分别约为 1271 / 507 / 356 亿美元，AWS 仍是利润最厚的核心资产。",
                "source_label": "Amazon earnings release",
            },
            {
                "title": "下一季指引",
                "text": "Q1 2026 收入指引区间为 1510 亿至 1555 亿美元，对应同比增长 5% 至 8%。",
                "source_label": "Amazon earnings release",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Andy Jassy",
                "quote": "We are innovating relentlessly across every customer experience.",
                "analysis": "管理层仍把零售体验、云基础设施和广告工具放在同一套效率提升逻辑里，说明 Amazon 的经营主线正在向平台化继续收敛。",
                "source_label": "Amazon earnings release",
            },
            {
                "speaker": "Management",
                "quote": "AWS、广告与第三方平台服务继续强化利润结构。",
                "analysis": "节日季收入不再只靠自营零售冲量，而是由更高质量的云与平台收入共同抬升经营利润。",
                "source_label": "Amazon earnings release",
            },
        ],
        "coverage_notes": [
            "当季结果、分部结构与下一季收入指引已切换到 Amazon 官方新闻稿口径。",
            "利润桥图页改用 Amazon 官方收入类别拆分，和圆环页的 North America / International / AWS 结构分工明确。",
            "由于长期结构化利润序列更接近经营利润，12 季利润趋势页以经营利润率为主线解读。",
        ],
        "sources": [
            {
                "label": "Amazon Q4 2025 earnings release",
                "url": "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Fourth-Quarter-Results/default.aspx",
                "kind": "official_release",
                "date": "2026-02-05",
            },
            {
                "label": "Amazon Q4 2025 earnings call",
                "url": "https://ir.aboutamazon.com/events/event-details/2026/Q4-2025-Amazoncom-Inc-Earnings-Conference-Call-/default.aspx",
                "kind": "call_summary",
                "date": "2026-02-05",
            },
        ],
    },
    ("meta", "2025Q4"): {
        "fiscal_label": "Q4 2025",
        "release_date": "2026-01-28",
        "period_end": "2025-12-31",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "call_summary"],
        "headline": "广告效率与 AI 基建扩张并行推进，Meta Q4 2025 继续用 Family of Apps 的利润池覆盖高投入周期。",
        "takeaways": [
            "收入 598.9 亿美元，同比增长 23.8%；净利润 227.7 亿美元，同比增长 9.3%，EPS 8.88。",
            "Family of Apps / Reality Labs 收入分别为 589.4 / 9.6 亿美元；Family of Apps 经营利润达到 304.9 亿美元，继续支撑整体现金流。",
            "经营利润 247.5 亿美元，成本和费用 351.5 亿美元，其中 R&D 达 123.4 亿美元，显示公司仍在加速 AI 基建与模型投入。",
            "Q1 2026 收入指引区间为 535 亿至 565 亿美元，全年资本开支展望抬升至 640 亿至 720 亿美元。",
        ],
        "latest_kpis": {
            "revenue_bn": 59.893,
            "revenue_yoy_pct": 23.8,
            "revenue_qoq_pct": 16.9,
            "gaap_gross_margin_pct": 81.8,
            "non_gaap_gross_margin_pct": 81.8,
            "operating_income_bn": 24.745,
            "net_income_bn": 22.768,
            "net_income_yoy_pct": 9.3,
            "operating_cash_flow_bn": None,
            "free_cash_flow_bn": None,
            "gaap_eps": 8.88,
            "non_gaap_eps": 8.88,
        },
        "guidance": {
            "mode": "official",
            "revenue_bn": 55.0,
            "comparison_revenue_bn": 59.893,
            "gaap_gross_margin_pct": None,
            "comparison_margin_pct": 81.8,
            "current_label": "本季收入",
            "comparison_label": "下一季收入指引中枢",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "官方给出 Q1 2026 收入指引 535 亿至 565 亿美元，并同步把全年资本开支展望抬升至 640 亿至 720 亿美元；利润率面板继续使用历史中枢作参考锚。",
        },
        "current_segments": [
            {"name": "Family of Apps", "value_bn": 58.938, "yoy_pct": 24.6},
            {"name": "Reality Labs", "value_bn": 0.955, "yoy_pct": -10.8},
        ],
        "income_statement": {
            "subtitle": "利润表页沿用 Meta 官方 segment 与费用科目，把主业现金牛和 AI 投入放到同一张桥图里。",
            "sources": [
                {"name": "Family of Apps", "value_bn": 58.938, "yoy_pct": 24.6},
                {"name": "Reality Labs", "value_bn": 0.955, "yoy_pct": -10.8},
            ],
            "opex_breakdown": [
                {"name": "Research and development", "value_bn": 12.337, "pct_of_revenue": 20.6, "color": "#E11D48"},
                {"name": "Marketing and sales", "value_bn": 4.866, "pct_of_revenue": 8.1, "color": "#F43F5E"},
                {"name": "General and administrative", "value_bn": 7.018, "pct_of_revenue": 11.7, "color": "#FB7185"},
            ],
            "below_operating_items": [
                {"name": "Taxes & other", "value_bn": 1.977, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "Family of Apps 现金牛", "value": "$58.9B revenue | $30.5B op profit", "note": "核心广告业务继续为 AI 与新业务投入提供资金池。", "color": "#0866FF"},
                {"title": "Reality Labs 仍在投入期", "value": "($5.0B) op loss", "note": "RL 亏损依旧明显，但仍是管理层主动押注。", "color": "#16A34A"},
                {"title": "Q1 指引稳健", "value": "$53.5B-$56.5B guide", "note": "广告需求与 AI 推荐效率的表述依然偏积极。", "color": "#0F172A"},
            ],
        },
        "management_themes": [
            {"label": "AI 推荐与广告效率", "score": 92, "note": "AI 推荐系统继续提升广告相关性与投放回报。"},
            {"label": "算力基础设施投入", "score": 86, "note": "资本开支继续上修，基础设施扩张仍是未来一年的主线。"},
            {"label": "Family of Apps 现金牛属性", "score": 84, "note": "核心广告平台仍在为新业务与 AI 投入提供强现金流。"},
            {"label": "Reality Labs 持续投入", "score": 62, "note": "Reality Labs 仍然亏损，但叙事价值没有被公司放弃。"},
        ],
        "qna_themes": [
            {"label": "资本开支路径", "score": 82, "note": "市场重点追问 capex 强度与未来几年折旧压力。"},
            {"label": "广告 load 与 pricing", "score": 75, "note": "广告业务高增长背后，用户时长、转化率与广告单价都很关键。"},
            {"label": "AI agent / assistant 变现", "score": 66, "note": "投资人关注 AI 产品如何从 engagement 走向收入。"},
            {"label": "Reality Labs 亏损边界", "score": 56, "note": "RL 投入何时见顶仍是多空分歧焦点。"},
        ],
        "risks": [
            {"label": "资本开支继续上修", "score": 63, "note": "更高 capex 会压缩未来数季的自由现金流弹性。"},
            {"label": "Reality Labs 长期亏损", "score": 51, "note": "新业务投入回报期长，容易拖累市场对利润率的耐心。"},
            {"label": "广告宏观波动", "score": 45, "note": "广告预算对宏观环境变化仍然敏感。"},
        ],
        "catalysts": [
            {"label": "广告效率持续提升", "score": 88, "note": "推荐系统持续改善会直接提升主业盈利质量。"},
            {"label": "WhatsApp / Reels 变现深化", "score": 73, "note": "新流量池商业化如果继续改善，结构会更均衡。"},
            {"label": "AI 产品商业化加快", "score": 68, "note": "AI assistant 与企业工具若出现更强变现，会打开新叙事。"},
        ],
        "evidence_cards": [
            {
                "title": "收入与净利润",
                "text": "官方披露 Q4 2025 收入 598.9 亿美元、经营利润 247.5 亿美元、净利润 227.7 亿美元、EPS 8.88。",
                "source_label": "Meta earnings release",
            },
            {
                "title": "业务结构",
                "text": "Family of Apps 收入约 589.4 亿美元、Reality Labs 收入约 9.6 亿美元；前者经营利润达到 304.9 亿美元，主业现金流地位依然稳固。",
                "source_label": "Meta earnings release",
            },
            {
                "title": "展望与投入",
                "text": "Q1 2026 收入指引为 535 亿至 565 亿美元，全年资本开支展望为 640 亿至 720 亿美元。",
                "source_label": "Meta earnings release",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Mark Zuckerberg",
                "quote": "We had a strong quarter both in our business and community.",
                "analysis": "管理层把广告业务表现与平台活跃度并读，意味着主业现金流依然是本轮 AI 投资周期最关键的底层支撑。",
                "source_label": "Meta earnings release",
            },
            {
                "speaker": "Management",
                "quote": "Meta AI usage is growing rapidly across our apps.",
                "analysis": "公司继续把 AI 视作提升广告效率和产品粘性的核心抓手，而不只是前端叙事。",
                "source_label": "Meta earnings release",
            },
        ],
        "coverage_notes": [
            "当季结果、业务结构与下一季收入指引已切换到 Meta 官方新闻稿口径。",
            "利润桥图页沿用官方 segment 收入，并把 R&D / 营销 / 行政费用映射到统一版式中。",
            "公司没有给出利润率数值指引，因此指引页利润率面板继续展示历史中枢参考值。",
        ],
        "sources": [
            {
                "label": "Meta Q4 2025 results",
                "url": "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-Fourth-Quarter-and-Full-Year-2025-Results/default.aspx",
                "kind": "official_release",
                "date": "2026-01-28",
            },
            {
                "label": "Meta investor relations",
                "url": "https://investor.atmeta.com/",
                "kind": "investor_relations",
                "date": "2026-01-28",
            },
        ],
    },
    ("tsla", "2025Q4"): {
        "fiscal_label": "Q4 2025",
        "release_date": "2026-01-28",
        "period_end": "2025-12-31",
        "coverage_months": ["2025-10", "2025-11", "2025-12"],
        "materials": ["earnings_release", "presentation", "call_summary"],
        "headline": "Tesla Q4 2025 汽车主业仍在调整，但储能扩张与正现金流继续为中期产品路线提供缓冲。",
        "takeaways": [
            "收入 249.0 亿美元，同比下降 3.1%；Automotive / Energy Generation and Storage / Services and Other 收入分别为 176.9 / 38.4 / 33.7 亿美元。",
            "储能继续成为最亮的结构变量，管理层明确表示 2026 年 Energy 业务增速仍将快于 Automotive 业务。",
            "经营利润 14.1 亿美元、净利润 8.4 亿美元；经营现金流 38.1 亿美元，自由现金流 14.2 亿美元，现金流仍维持为正。",
            "公司没有给出明确季度收入指引，官方材料重点继续放在更低价新车型、自动驾驶路线与储能扩产。",
        ],
        "latest_kpis": {
            "revenue_bn": 24.901,
            "revenue_yoy_pct": -3.1,
            "revenue_qoq_pct": -11.4,
            "gaap_gross_margin_pct": 20.1,
            "non_gaap_gross_margin_pct": 20.1,
            "operating_income_bn": 1.409,
            "net_income_bn": 0.840,
            "net_income_yoy_pct": -60.5,
            "operating_cash_flow_bn": 3.813,
            "free_cash_flow_bn": 1.420,
            "gaap_eps": None,
            "non_gaap_eps": None,
        },
        "guidance": {
            "mode": "official_context",
            "current_label": "本季收入",
            "comparison_label": "近四季季度均值",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "近四季平均毛利率",
            "commentary": "公司没有给出明确季度收入指引，本页用经营基线承接官方叙事；更关键的跟踪点仍是新车型节奏、FSD / Robotaxi 路径与储能扩产兑现。",
        },
        "current_segments": [
            {"name": "Automotive", "value_bn": 17.693},
            {"name": "Energy Generation and Storage", "value_bn": 3.837},
            {"name": "Services and Other", "value_bn": 3.371},
        ],
        "income_statement": {
            "subtitle": "利润表页按 Tesla 官方 shareholder deck 的收入、费用与经营利润路径绘制，保证桥图和报表逻辑一致。",
            "sources": [
                {"name": "Automotive", "value_bn": 17.693},
                {"name": "Energy Generation and Storage", "value_bn": 3.837},
                {"name": "Services and Other", "value_bn": 3.371},
            ],
            "opex_breakdown": [
                {"name": "Operating expenses", "value_bn": 3.600, "pct_of_revenue": 14.5, "color": "#E11D48"},
            ],
            "below_operating_items": [
                {"name": "Tax & other", "value_bn": 0.569, "color": "#D92D20"},
            ],
            "annotations": [
                {"title": "Energy 成为第二增长极", "value": "$3.84B revenue", "note": "管理层预计 2026 年 Energy 仍将快于汽车业务增长。", "color": "#10B981"},
                {"title": "汽车业务仍是主盘", "value": "$17.69B automotive", "note": "汽车收入仍然决定整体规模与利润率方向。", "color": "#DC2626"},
                {"title": "现金流仍为正", "value": "$3.81B OCF | $1.42B FCF", "note": "在主业承压期，正现金流仍是重要底线。", "color": "#64748B"},
            ],
        },
        "management_themes": [
            {"label": "储能继续扩张", "score": 86, "note": "储能已成为汽车之外最清晰的结构亮点与增长缓冲器。"},
            {"label": "自动驾驶与 Robotaxi", "score": 79, "note": "市场仍把 FSD 与 Robotaxi 进展视为估值最核心的远期变量。"},
            {"label": "汽车利润率保卫", "score": 72, "note": "价格策略、成本控制与车型 mix 共同决定汽车利润率。"},
            {"label": "现金流韧性", "score": 66, "note": "在汽车收入承压时仍维持正自由现金流，是当前底线之一。"},
        ],
        "qna_themes": [
            {"label": "新车型与低价平台进度", "score": 78, "note": "市场最关心新车型节奏能否重新带动交付增长。"},
            {"label": "FSD 商业化兑现", "score": 74, "note": "自动驾驶从技术演示走向更明确货币化仍是关键。"},
            {"label": "储能产能与需求", "score": 70, "note": "储能业务能否继续高速扩张，决定结构改善能否延续。"},
            {"label": "汽车利润率底部", "score": 62, "note": "价格竞争尚未完全结束时，利润率何时企稳是焦点。"},
        ],
        "risks": [
            {"label": "汽车交付继续承压", "score": 66, "note": "需求与竞争如果继续恶化，收入与利润率都会承压。"},
            {"label": "自动驾驶兑现时间拉长", "score": 55, "note": "Robotaxi / FSD 若继续延后，估值叙事会受损。"},
            {"label": "利润率反复", "score": 49, "note": "价格与成本之间的拉扯仍会使利润率波动偏大。"},
        ],
        "catalysts": [
            {"label": "储能继续高增", "score": 87, "note": "储能如果持续跑赢汽车业务，结构质量会明显改善。"},
            {"label": "自动驾驶里程碑", "score": 76, "note": "更明确的 FSD / Robotaxi 进展会快速抬升市场预期。"},
            {"label": "成本优化兑现", "score": 65, "note": "若单车成本继续改善，利润率修复空间会更大。"},
        ],
        "evidence_cards": [
            {
                "title": "现金流质量",
                "text": "官方 shareholder deck 披露经营现金流 38.1 亿美元、自由现金流 14.2 亿美元，现金流仍为正。",
                "source_label": "Tesla Q4 2025 update deck",
            },
            {
                "title": "结构拆分",
                "text": "Automotive / Energy Generation and Storage / Services and Other 收入分别约为 176.9 / 38.4 / 33.7 亿美元；储能继续是最亮的结构变量。",
                "source_label": "Tesla Q4 2025 update deck",
            },
            {
                "title": "研究主线",
                "text": "官方材料继续把新车型、自动驾驶与储能扩产放在中期叙事中心，而不是给出短期收入数字承诺；本季经营利润仍高于净利润。",
                "source_label": "Tesla shareholder deck",
            },
        ],
        "call_quote_cards": [
            {
                "speaker": "Management",
                "quote": "We expect Energy to grow faster than the Automotive business in 2026.",
                "analysis": "这说明 Tesla 正在把储能从“补充故事”逐步拉升为真正能对冲汽车波动的第二增长曲线。",
                "source_label": "Tesla Q4 2025 shareholder deck",
            },
            {
                "speaker": "Management",
                "quote": "Our roadmap for new vehicles remains on track for start of production in 2026.",
                "analysis": "管理层仍把更低价新车型视为重启交付节奏的关键节点，时间兑现度会直接影响市场预期。",
                "source_label": "Tesla Q4 2025 shareholder deck",
            },
        ],
        "coverage_notes": [
            "当季结果与结构拆分已切换到 Tesla 官方季度 update deck 口径。",
            "利润桥图页已回到官方经营利润高于净利润的真实报表路径，不再错误展示正向非经营项。",
            "公司没有给出明确季度收入指引，因此指引页以官方叙事语境叠加经营基线展示。",
        ],
        "sources": [
            {
                "label": "Tesla Q4 2025 shareholder deck",
                "url": "https://ir.tesla.com/_flysystem/s3/sec/000162828026003837/tsla-20260128-gen.pdf",
                "kind": "presentation",
                "date": "2026-01-28",
            },
        ],
    },
}
