from __future__ import annotations

from typing import Optional

from .official_fixtures import BRAND_SEGMENT_COLOR_UPDATES, OFFICIAL_MAG7_FIXTURES


DEFAULT_SUPPORTED_QUARTERS = [
    "2024Q1",
    "2024Q2",
    "2024Q3",
    "2024Q4",
    "2025Q1",
    "2025Q2",
    "2025Q3",
    "2025Q4",
]


def build_company(
    company_id: str,
    name: str,
    english_name: str,
    ticker: str,
    description: str,
    primary: str,
    secondary: str,
    accent: str,
    surface: str,
    data_provider: str,
    slug: str,
    local_series_key: Optional[str] = None,
    money_symbol: str = "$",
    currency_code: str = "USD",
    structure_priority: Optional[list[str]] = None,
    card_headline: Optional[str] = None,
    ir_url: Optional[str] = None,
    display_order: int = 99,
    quarter_label_mode: Optional[str] = None,
    historical_profit_basis: str = "net_income",
    historical_profit_label: str = "净利润",
    historical_profit_margin_label: str = "净利率",
    official_source: Optional[dict[str, object]] = None,
    segment_order: Optional[list[str]] = None,
    segment_aliases: Optional[dict[str, str]] = None,
    theme_pattern: str = "halo",
) -> dict[str, object]:
    return {
        "id": company_id,
        "name": name,
        "english_name": english_name,
        "ticker": ticker,
        "slug": slug,
        "description": description,
        "card_headline": card_headline or description,
        "data_provider": data_provider,
        "series_key": local_series_key or company_id,
        "money_symbol": money_symbol,
        "currency_code": currency_code,
        "brand": {
            "primary": primary,
            "secondary": secondary,
            "accent": accent,
            "surface": surface,
            "segment_colors": {},
            "theme_pattern": theme_pattern,
        },
        "structure_priority": structure_priority or ["management"],
        "supported_quarters": list(DEFAULT_SUPPORTED_QUARTERS),
        "ir_url": ir_url or "",
        "display_order": display_order,
        "quarter_label_mode": quarter_label_mode or "natural",
        "historical_profit_basis": historical_profit_basis,
        "historical_profit_label": historical_profit_label,
        "historical_profit_margin_label": historical_profit_margin_label,
        "official_source": dict(official_source or {}),
        "segment_order": list(segment_order or []),
        "segment_aliases": dict(segment_aliases or {}),
    }


COMPANY_REGISTRY = {
    "nvidia": build_company(
        "nvidia",
        "英伟达",
        "NVIDIA",
        "NVDA",
        "以 AI 计算基础设施、GPU、网络和软件栈为核心的高增长平台型公司。",
        "#76B900",
        "#0F172A",
        "#E5F6BA",
        "#F6FAEC",
        "local",
        "nvda",
        local_series_key="nvidia",
        structure_priority=["segment", "product", "management"],
        card_headline="AI 资本开支最强 beta 之一，12 季结构迁移最为剧烈。",
        ir_url="https://investor.nvidia.com/",
        display_order=1,
        official_source={
            "sec_cik": "0001045810",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 1,
        },
        segment_order=["Data Center", "Gaming", "Professional Visualization", "Automotive", "OEM and Other"],
    ),
    "apple": build_company(
        "apple",
        "苹果",
        "Apple",
        "AAPL",
        "消费电子与服务生态双轮驱动的现金流平台型公司。",
        "#111827",
        "#2563EB",
        "#DBEAFE",
        "#F8FAFC",
        "local",
        "aapl",
        local_series_key="apple",
        structure_priority=["segment", "management"],
        card_headline="硬件周期与服务收入质量共同决定利润弹性。",
        ir_url="https://investor.apple.com/",
        display_order=2,
        official_source={
            "sec_cik": "0000320193",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "discovery_sitemaps": ["https://www.apple.com/newsroom/sitemap.xml"],
            "fiscal_year_end_month": 9,
        },
        segment_order=["iPhone", "Mac", "iPad", "Wearables, Home and Accessories", "Services", "Products"],
        segment_aliases={"Wearables, Home & Accessories": "Wearables, Home and Accessories"},
    ),
    "alphabet": build_company(
        "alphabet",
        "谷歌",
        "Alphabet",
        "GOOGL",
        "搜索广告、云与 AI 基础设施共同推动利润率和资本开支周期。",
        "#2563EB",
        "#0F172A",
        "#DBEAFE",
        "#F8FAFC",
        "local",
        "googl",
        local_series_key="alphabet",
        structure_priority=["segment", "management"],
        card_headline="广告韧性与云业务利润兑现是核心观察点。",
        ir_url="https://abc.xyz/investor/",
        display_order=3,
        official_source={
            "sec_cik": "0001652044",
            "historical_sec_ciks": [
                {
                    "through": "2015Q3",
                    "sec_cik": "0001288776",
                }
            ],
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "discovery_sitemaps": ["https://abc.xyz/sitemap.xml"],
        },
        segment_order=[
            "Google properties",
            "Google Services",
            "Google Search & other",
            "YouTube ads",
            "Google Network",
            "Google other",
            "Google subscriptions, platforms, and devices",
            "Google Cloud",
            "Other Bets",
        ],
        segment_aliases={
            "Google subscriptions, platforms & devices": "Google subscriptions, platforms, and devices",
            "Google properties revenues": "Google properties",
            "Google other revenues": "Google other",
        },
    ),
    "microsoft": build_company(
        "microsoft",
        "微软",
        "Microsoft",
        "MSFT",
        "云平台、Office 订阅和企业软件生态带来高质量复利增长。",
        "#0078D4",
        "#0F172A",
        "#DCEFFD",
        "#F7FBFF",
        "local",
        "msft",
        local_series_key="microsoft",
        structure_priority=["segment", "management"],
        card_headline="Azure、Copilot 与企业 IT 开支节奏是主线。",
        ir_url="https://www.microsoft.com/en-us/Investor/",
        display_order=4,
        official_source={
            "sec_cik": "0000789019",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 6,
        },
        segment_order=["Productivity and Business Processes", "Intelligent Cloud", "More Personal Computing"],
        segment_aliases={"Productivity & Business Processes": "Productivity and Business Processes"},
    ),
    "amazon": build_company(
        "amazon",
        "亚马逊",
        "Amazon",
        "AMZN",
        "电商、广告与 AWS 的复合型平台，利润结构持续改善。",
        "#F59E0B",
        "#111827",
        "#FEF3C7",
        "#FFFBEB",
        "local",
        "amzn",
        local_series_key="amazon",
        structure_priority=["segment", "management"],
        card_headline="AWS 增速、零售利润率和广告贡献一起决定估值中枢。",
        ir_url="https://ir.aboutamazon.com/",
        display_order=5,
        official_source={
            "sec_cik": "0001018724",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=[
            "North America",
            "International",
            "AWS",
            "Online stores",
            "Third-party seller services",
            "Advertising services",
            "Subscription services",
            "Physical stores",
            "Other",
        ],
    ),
    "tsmc": build_company(
        "tsmc",
        "台积电",
        "TSMC",
        "TSM",
        "全球最重要的先进制程晶圆代工平台，AI 需求与制程升级共振。",
        "#B91C1C",
        "#0F172A",
        "#FEE2E2",
        "#FFF7F7",
        "local",
        "tsm",
        local_series_key="tsmc",
        structure_priority=["segment", "management"],
        card_headline="先进制程产能利用率与 AI/HPC 占比是核心指标。",
        ir_url="https://investor.tsmc.com/",
        display_order=6,
        official_source={
            "sec_cik": "0001046179",
            "release_forms": ["6-K"],
            "filing_forms": ["6-K"],
            "release_document_hints": ["quarter", "withguidance", "results"],
            "release_document_excludes": ["monthend", "revenue", "dividend", "board", "treasury", "change", "media", "agm"],
            "filing_document_excludes": ["monthend", "revenue", "dividend", "board", "treasury", "change", "media", "agm"],
        },
        segment_order=["HPC", "Smartphone", "Internet of Things", "Automotive", "DCE", "Others"],
    ),
    "meta": build_company(
        "meta",
        "Meta",
        "Meta",
        "META",
        "广告现金牛与 AI / Reality Labs 投入并存的平台型公司。",
        "#0866FF",
        "#0F172A",
        "#D7E9FF",
        "#F7FBFF",
        "local",
        "meta",
        local_series_key="meta",
        structure_priority=["segment", "management"],
        card_headline="广告 ROI、AI 推荐效率与资本开支节奏是重点。",
        ir_url="https://investor.atmeta.com/",
        display_order=7,
        official_source={
            "sec_cik": "0001326801",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=["Family of Apps", "Reality Labs"],
    ),
    "avgo": build_company(
        "avgo",
        "博通",
        "Broadcom",
        "AVGO",
        "由 AI 半导体与基础设施软件双轮驱动、现金流质量突出的平台型公司。",
        "#C62828",
        "#12263F",
        "#FCE7E7",
        "#FFF5F5",
        "local",
        "avgo",
        local_series_key="avgo",
        structure_priority=["segment", "management"],
        card_headline="AI 半导体景气与软件利润池共同支撑盈利能力。",
        ir_url="https://investors.broadcom.com/",
        display_order=8,
        official_source={
            "sec_cik": "0001730168",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 11,
        },
        segment_order=["Semiconductor Solutions", "Infrastructure Software"],
    ),
    "tsla": build_company(
        "tsla",
        "特斯拉",
        "Tesla",
        "TSLA",
        "电动车、储能与自动驾驶叙事交织的高波动平台型资产。",
        "#111827",
        "#DC2626",
        "#FEE2E2",
        "#FFF7F7",
        "local",
        "tsla",
        local_series_key="tsla",
        structure_priority=["segment", "management"],
        card_headline="交付节奏、毛利率和 FSD 兑现预期决定市场叙事。",
        ir_url="https://ir.tesla.com/",
        display_order=9,
        official_source={
            "sec_cik": "0001318605",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=["Automotive", "Energy Generation and Storage", "Services and Other"],
    ),
    "berkshire": build_company(
        "berkshire",
        "伯克希尔哈撒韦",
        "Berkshire Hathaway",
        "BRK.B",
        "保险浮存金、铁路、公用事业与股票投资组合共同构成的复合型控股公司。",
        "#4B5563",
        "#111827",
        "#E5E7EB",
        "#F9FAFB",
        "stockanalysis",
        "brk.b",
        card_headline="保险承保、投资收益与现金仓位共同决定季度波动。",
        ir_url="https://www.berkshirehathaway.com/",
        display_order=10,
        official_source={
            "sec_cik": "0001067983",
            "release_forms": ["8-K"],
            "filing_forms": ["10-K"],
        },
        segment_order=[
            "Insurance underwriting",
            "Insurance investment income",
            "BNSF",
            "Berkshire Hathaway Energy",
            "Manufacturing, service and retailing",
        ],
    ),
    "walmart": build_company(
        "walmart",
        "沃尔玛",
        "Walmart",
        "WMT",
        "零售规模优势、会员与供应链效率共同驱动现金流的防御型龙头。",
        "#0A5CC0",
        "#0F172A",
        "#D9EAFE",
        "#F7FBFF",
        "stockanalysis",
        "wmt",
        card_headline="同店增长、毛利率和电商效率是最核心的边际变量。",
        ir_url="https://stock.walmart.com/",
        display_order=11,
        quarter_label_mode="by_period_end_majority",
        official_source={
            "sec_cik": "0000104169",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 1,
        },
        segment_order=["Walmart U.S.", "Walmart International", "Sam's Club U.S."],
    ),
    "mcdonalds": build_company(
        "mcdonalds",
        "麦当劳",
        "McDonald's",
        "MCD",
        "全球快餐连锁龙头，以直营与加盟并行模式驱动高利润率和稳定现金流。",
        "#DA291C",
        "#FFC72C",
        "#FDE7E3",
        "#FFF9F2",
        "stockanalysis",
        "mcd",
        card_headline="同店销售、加盟租金与餐厅利润率共同决定业绩韧性。",
        ir_url="https://investor.mcdonalds.com/",
        display_order=12,
        official_source={
            "sec_cik": "0000063908",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "discovery_sitemaps": ["https://corporate.mcdonalds.com/content/dam/sites/corp/nfl/json/sitemap.json"],
            "fiscal_year_end_month": 12,
        },
        segment_order=[
            "U.S.",
            "International Operated Markets",
            "International Developmental Licensed Markets & Corporate",
        ],
    ),
    "starbucks": build_company(
        "starbucks",
        "星巴克",
        "Starbucks",
        "SBUX",
        "全球咖啡连锁龙头，以门店效率、会员运营和国际扩张驱动长期增长。",
        "#006241",
        "#1F2937",
        "#DCFCE7",
        "#F6FFF9",
        "stockanalysis",
        "sbux",
        card_headline="同店销售、客单价与中国及北美门店效率是核心观察点。",
        ir_url="https://investor.starbucks.com/",
        display_order=13,
        quarter_label_mode="by_period_end_majority",
        official_source={
            "sec_cik": "0000829224",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 9,
        },
        segment_order=["North America", "International", "Channel Development", "Corporate and Other"],
    ),
    "lly": build_company(
        "lly",
        "礼来",
        "Eli Lilly",
        "LLY",
        "由减重与糖尿病产品拉动的高景气创新药平台。",
        "#E11D48",
        "#0F172A",
        "#FCE7F3",
        "#FFF7FB",
        "stockanalysis",
        "lly",
        card_headline="GLP-1 放量与产能扩张共同主导业绩波动。",
        ir_url="https://investor.lilly.com/",
        display_order=12,
        official_source={
            "sec_cik": "0000059478",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=["Mounjaro", "Zepbound", "Verzenio", "Jardiance"],
    ),
    "jpm": build_company(
        "jpm",
        "摩根大通",
        "JPMorgan Chase",
        "JPM",
        "美国系统性重要银行龙头，利差、投行与信用成本共同驱动利润。",
        "#1F2937",
        "#2563EB",
        "#DBEAFE",
        "#F7FBFF",
        "stockanalysis",
        "jpm",
        card_headline="净息差、交易投行收入和拨备节奏是主要观察轴。",
        ir_url="https://www.jpmorganchase.com/ir",
        display_order=13,
        official_source={
            "sec_cik": "0000019617",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=[
            "Consumer & Community Banking",
            "Commercial & Investment Bank",
            "Asset & Wealth Management",
            "Commercial Banking",
        ],
    ),
    "xom": build_company(
        "xom",
        "埃克森美孚",
        "Exxon Mobil",
        "XOM",
        "上游、下游与化工一体化的能源龙头，现金流高度受油气价格驱动。",
        "#D32F2F",
        "#0F172A",
        "#FEE2E2",
        "#FFF7F7",
        "stockanalysis",
        "xom",
        card_headline="油气价格、炼化裂解价差与资本回报决定季度节奏。",
        ir_url="https://corporate.exxonmobil.com/investors",
        display_order=14,
        official_source={
            "sec_cik": "0000034088",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
    ),
    "jnj": build_company(
        "jnj",
        "强生",
        "Johnson & Johnson",
        "JNJ",
        "医药与医疗器械双主线并行的防御型医疗龙头。",
        "#B91C1C",
        "#0F172A",
        "#FEE2E2",
        "#FFF7F7",
        "stockanalysis",
        "jnj",
        card_headline="药品增长、器械恢复与诉讼事件共同影响估值稳定性。",
        ir_url="https://investor.jnj.com/",
        display_order=15,
        official_source={
            "sec_cik": "0000200406",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
        },
        segment_order=["Consumer Health", "Pharmaceutical", "Innovative Medicine", "MedTech"],
        segment_aliases={
            "Medical Devices": "MedTech",
        },
    ),
    "visa": build_company(
        "visa",
        "维萨",
        "Visa",
        "V",
        "全球支付网络龙头，交易量、跨境恢复与运营杠杆是核心逻辑。",
        "#1A1F71",
        "#F59E0B",
        "#E0E7FF",
        "#F8FAFF",
        "stockanalysis",
        "v",
        card_headline="支付量、跨境消费与费率稳定性决定盈利质量。",
        ir_url="https://investor.visa.com/",
        display_order=16,
        official_source={
            "sec_cik": "0001403161",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 9,
        },
        segment_order=["Data processing revenue", "Service revenue", "International transaction revenue", "Other revenue"],
    ),
    "asml": build_company(
        "asml",
        "阿斯麦",
        "ASML",
        "ASML",
        "光刻设备垄断龙头，订单节奏与先进制程资本开支高度相关。",
        "#1D4ED8",
        "#0F172A",
        "#DBEAFE",
        "#F7FBFF",
        "stockanalysis",
        "asml",
        money_symbol="EUR ",
        currency_code="EUR",
        card_headline="EUV/DUV 出货与晶圆厂资本开支决定景气波动。",
        ir_url="https://www.asml.com/en/investors",
        display_order=17,
        official_source={
            "sec_cik": "0000937966",
            "release_forms": ["6-K"],
            "filing_forms": ["6-K", "20-F"],
            "release_document_hints": [
                "q1results",
                "q2results",
                "q3results",
                "q4results",
                "quarterlyresul",
                "financialresul",
                "asml reports",
            ],
            "release_document_excludes": ["agm", "annualreport", "litigation", "settle", "nikon", "zeiss"],
            "filing_document_excludes": ["agm", "annualreport"],
            "attachment_profiles": [
                {
                    "kind": "official_release",
                    "role": "earnings_release",
                    "hints": [
                        "q1results",
                        "q2results",
                        "q3results",
                        "q4results",
                        "quarterlyresul",
                        "financialresul",
                        "press release",
                    ],
                    "excludes": [
                        "litigation",
                        "settle",
                        "nikon",
                        "zeiss",
                        "presentation",
                        "deck",
                        "slides",
                        "buy back",
                        "buyback",
                        "share buy back",
                        "share buyback",
                        "repurchase",
                        "transaction",
                        "regulatory approvals",
                    ],
                },
                {
                    "kind": "presentation",
                    "role": "earnings_presentation",
                    "hints": ["presentation", "investor", "dex992", "99.2", "ex-99-2", "results summary"],
                    "excludes": ["litigation", "settle", "nikon", "zeiss", "webcast", "transcript", "buyback", "repurchase", "transaction"],
                },
                {
                    "kind": "call_summary",
                    "role": "earnings_call",
                    "hints": ["webcast", "transcript", "conference call", "earnings call"],
                    "excludes": ["litigation", "settle", "nikon", "zeiss", "presentation"],
                },
            ],
        },
        segment_order=["Net system sales", "Installed Base Management"],
    ),
    "samsung": build_company(
        "samsung",
        "三星电子",
        "Samsung Electronics",
        "SSNLF",
        "全球消费电子、存储、晶圆代工与移动终端龙头，盈利弹性受半导体景气与终端需求共同驱动。",
        "#1428A0",
        "#0F172A",
        "#DBE5FF",
        "#F7F9FF",
        "stockanalysis",
        "ssnlf",
        money_symbol="₩",
        currency_code="KRW",
        structure_priority=["segment", "management"],
        card_headline="存储价格周期、HBM/先进封装推进与移动终端盈利修复是主线。",
        ir_url="https://images.samsung.com/is/content/samsung/assets/global/ir/docs/",
        display_order=18,
    ),
    "micron": build_company(
        "micron",
        "美光科技",
        "Micron",
        "MU",
        "存储周期与高带宽内存需求共振的半导体周期龙头。",
        "#2563EB",
        "#0F172A",
        "#DBEAFE",
        "#F7FBFF",
        "stockanalysis",
        "mu",
        card_headline="HBM、DRAM 定价与库存周期决定盈利弹性。",
        ir_url="https://investors.micron.com/",
        display_order=18,
        quarter_label_mode="by_period_end_majority",
        official_source={
            "sec_cik": "0000723125",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 8,
        },
        segment_order=[
            "Cloud Memory Business Unit",
            "Core Data Center Business Unit",
            "Mobile and Client Business Unit",
            "Automotive and Embedded Business Unit",
        ],
    ),
    "oracle": build_company(
        "oracle",
        "甲骨文",
        "Oracle",
        "ORCL",
        "数据库与云基础设施并行推进、利润率稳定的企业软件平台。",
        "#C74634",
        "#0F172A",
        "#FCE7E4",
        "#FFF7F6",
        "stockanalysis",
        "orcl",
        card_headline="云基础设施扩张与数据库维护收入共同决定增长质量。",
        ir_url="https://www.oracle.com/investor/",
        display_order=20,
        quarter_label_mode="by_period_end_majority",
        official_source={
            "sec_cik": "0001341439",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 5,
        },
        segment_order=["Cloud", "Software", "Hardware", "Services"],
    ),
    "ibm": build_company(
        "ibm",
        "IBM",
        "IBM",
        "IBM",
        "企业软件、咨询与基础设施并行推进的全球 IT 平台型公司。",
        "#0F62FE",
        "#161616",
        "#D0E2FF",
        "#F4F9FF",
        "stockanalysis",
        "ibm",
        card_headline="软件增长、咨询恢复与大型主机周期共同决定利润弹性。",
        ir_url="https://www.ibm.com/investor/",
        display_order=21,
        official_source={
            "sec_cik": "0000051143",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 12,
        },
        segment_order=["Software", "Consulting", "Infrastructure", "Financing"],
    ),
    "costco": build_company(
        "costco",
        "好市多",
        "Costco",
        "COST",
        "会员模式与高周转零售效率共同驱动的高质量消费龙头。",
        "#DC2626",
        "#1D4ED8",
        "#FEE2E2",
        "#FFF8F8",
        "stockanalysis",
        "cost",
        card_headline="会员费、同店销售与库存效率构成长期复利核心。",
        ir_url="https://investor.costco.com/",
        display_order=19,
        quarter_label_mode="by_period_end_majority",
        official_source={
            "sec_cik": "0000909832",
            "release_forms": ["8-K"],
            "filing_forms": ["10-Q", "10-K"],
            "fiscal_year_end_month": 8,
        },
        segment_order=["Net sales", "Membership fees"],
    ),
}


COMPANY_REGISTRY["nvidia"]["brand"]["segment_colors"] = {
    "Data Center": "#76B900",
    "Gaming": "#0EA5A0",
    "Professional Visualization": "#5D7CE2",
    "Automotive": "#F59E0B",
    "OEM and Other": "#94A3B8",
}
COMPANY_REGISTRY["avgo"]["brand"]["segment_colors"] = {
    "Semiconductor Solutions": "#C62828",
    "Infrastructure Software": "#1E5AA8",
}
BRAND_THEME_PATTERN_UPDATES = {
    "nvidia": "matrix",
    "apple": "glass",
    "alphabet": "spectrum",
    "microsoft": "grid",
    "amazon": "arc",
    "tsmc": "ring",
    "meta": "orbit",
    "avgo": "circuit",
    "tsla": "velocity",
    "berkshire": "ledger",
    "walmart": "retail",
    "lly": "clinical",
    "jpm": "ledger",
    "xom": "industrial",
    "jnj": "clinical",
    "visa": "ledger",
    "asml": "precision",
    "micron": "circuit",
    "oracle": "circuit",
    "ibm": "grid",
    "costco": "retail",
}
SEGMENT_ALIAS_UPDATES = {
    "apple": {
        "Wearables, Home & Accessories": "Wearables, Home and Accessories",
        "iPhone and related products and services": "iPhone",
        "Total iPhone net sales": "iPhone",
        "iPad and related products and services": "iPad",
        "Total Macintosh net sales": "Mac",
        "Total Mac net sales": "Mac",
        "Peripherals and other hardware": "Wearables, Home and Accessories",
        "Software, service and other sales": "Services",
        "Software, service, and other sales": "Services",
        "Software, service, and other sales h": "Services",
        "Software and service": "Services",
        "Services and other": "Services",
    },
    "alphabet": {
        "Google subscriptions, platforms & devices": "Google subscriptions, platforms, and devices",
        "Google subscriptions platforms and devices": "Google subscriptions, platforms, and devices",
        "Google Search": "Google Search & other",
        "Google Search and other": "Google Search & other",
        "Google Search & Other": "Google Search & other",
        "Google Search other": "Google Search & other",
        "YouTube advertising": "YouTube ads",
        "YouTube Ads": "YouTube ads",
        "Google Network Members' properties": "Google Network",
        "Google Network members' properties": "Google Network",
        "Google Network revenues": "Google Network",
        "Network Members properties": "Google Network",
        "Google other": "Google subscriptions, platforms, and devices",
        "Google Other": "Google subscriptions, platforms, and devices",
        "Google subscriptions": "Google subscriptions, platforms, and devices",
    },
    "microsoft": {
        "Productivity & Business Processes": "Productivity and Business Processes",
        "Productivity and Business Process": "Productivity and Business Processes",
        "Intelligent cloud": "Intelligent Cloud",
        "More personal computing": "More Personal Computing",
        "Office Commercial products and cloud services": "Productivity and Business Processes",
        "Office Commercial": "Productivity and Business Processes",
        "Office Consumer": "Productivity and Business Processes",
        "LinkedIn": "Productivity and Business Processes",
        "Dynamics products and cloud services": "Productivity and Business Processes",
        "Dynamics": "Productivity and Business Processes",
        "Server products and cloud services": "Intelligent Cloud",
        "Enterprise Services": "Intelligent Cloud",
        "Azure": "Intelligent Cloud",
        "Windows OEM": "More Personal Computing",
        "Windows Commercial products and cloud services": "More Personal Computing",
        "Devices": "More Personal Computing",
        "Xbox content and services": "More Personal Computing",
        "Search and news advertising": "More Personal Computing",
    },
    "amazon": {
        "North america": "North America",
        "Aws": "AWS",
        "Amazon Web Services": "AWS",
        "Amazon web services": "AWS",
        "Online stores revenue": "Online stores",
        "Third-party seller services revenue": "Third-party seller services",
        "Advertising services revenue": "Advertising services",
        "Subscription services revenue": "Subscription services",
        "Physical stores revenue": "Physical stores",
    },
    "berkshire": {
        "Insurance underwriting revenues": "Insurance underwriting",
        "Insurance-underwriting": "Insurance underwriting",
        "Insurance investment income": "Insurance investment income",
        "Insurance-investment income": "Insurance investment income",
        "BNSF Railway": "BNSF",
        "Berkshire Hathaway Energy Company": "Berkshire Hathaway Energy",
        "Manufacturing": "Manufacturing, service and retailing",
        "Service": "Manufacturing, service and retailing",
        "Retailing": "Manufacturing, service and retailing",
        "Manufacturing, service and retailing businesses": "Manufacturing, service and retailing",
    },
    "tsmc": {
        "Internet Of Things": "Internet of Things",
    },
}
REPORT_STYLE_UPDATES = {
    "nvidia": {
        "cover_eyebrow": "AI Infrastructure Readout",
        "quarterly_label": "Execution Layer",
        "historical_label": "Capacity Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕训练/推理需求、系统交付、毛利兑现与现金回笼来读这一季。",
        "quarterly_lens": "训练/推理需求、Blackwell 交付节奏与毛利兑现",
        "historical_lens": "数据中心集中度、平台迁移与利润兑现斜率",
        "evidence_lens": "财报新闻稿、演示稿与管理层对需求边界的原文",
    },
    "apple": {
        "cover_eyebrow": "Ecosystem Readout",
        "quarterly_label": "Product Layer",
        "historical_label": "Installed Base Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕硬件周期、服务变现、地区需求与 installed base 扩张来读这一季。",
        "quarterly_lens": "产品周期、服务 mix 与地区需求强弱",
        "historical_lens": "iPhone 占比、Services 抬升与生态变现质量",
        "evidence_lens": "newsroom 原文、10-Q/10-K 表格与管理层关于 installed base / AI 的表述",
    },
    "alphabet": {
        "cover_eyebrow": "Ads + Cloud Readout",
        "quarterly_label": "Monetization Layer",
        "historical_label": "Platform Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕搜索广告韧性、云利润兑现与 AI 投入转收入的节奏来读这一季。",
        "quarterly_lens": "广告 monetization、Cloud 利润率与 AI 变现线索",
        "historical_lens": "搜索、Cloud 与订阅设备收入结构迁移",
        "evidence_lens": "股东信、电话会与对 capex / AI monetization 的原文",
    },
    "microsoft": {
        "cover_eyebrow": "Enterprise Platform Readout",
        "quarterly_label": "Platform Layer",
        "historical_label": "Compounding Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 Azure、Copilot、企业软件粘性与经营杠杆来读这一季。",
        "quarterly_lens": "Azure 增速、Copilot 附加值与企业 IT 开支",
        "historical_lens": "Cloud 权重抬升、平台复利与利润质量",
        "evidence_lens": "财报稿、管理层电话会与 Azure / Copilot 的官方措辞",
    },
    "amazon": {
        "cover_eyebrow": "Retail + AWS Readout",
        "quarterly_label": "Fulfillment Layer",
        "historical_label": "Mix Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕零售效率、AWS 增速、广告兑现与现金流杠杆来读这一季。",
        "quarterly_lens": "履约效率、AWS 增长与广告盈利贡献",
        "historical_lens": "AWS / 零售 / 广告 mix 变化与利润改善",
        "evidence_lens": "股东信、8-K 与管理层对消费和云需求的原文",
    },
    "tsmc": {
        "cover_eyebrow": "Foundry Cycle Readout",
        "quarterly_label": "Node Layer",
        "historical_label": "Utilization Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕先进制程、HPC 占比、产能利用率与美元收入节奏来读这一季。",
        "quarterly_lens": "先进制程 mix、HPC / Smartphone 结构与汇率影响",
        "historical_lens": "HPC 权重抬升、制程迁移与利润兑现",
        "evidence_lens": "法说会讲稿、季度 presentation 与官网新闻稿原文",
    },
    "meta": {
        "cover_eyebrow": "Attention Platform Readout",
        "quarterly_label": "Engagement Layer",
        "historical_label": "Monetization Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕广告 ROI、推荐效率、AI 投入与 Reality Labs 亏损边界来读这一季。",
        "quarterly_lens": "广告效率、推荐系统与资本开支边界",
        "historical_lens": "Family of Apps 现金牛与 Reality Labs 拖累的长期变化",
        "evidence_lens": "earnings release、prepared remarks 与 AI/capex 原文",
    },
    "avgo": {
        "cover_eyebrow": "Silicon + Software Readout",
        "quarterly_label": "Execution Layer",
        "historical_label": "Mix Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 AI 半导体景气、网络侧弹性与软件利润池来读这一季。",
        "quarterly_lens": "AI networking、半导体供需与软件现金流",
        "historical_lens": "半导体 / 软件 mix 与利润率稳定性",
        "evidence_lens": "财报稿、投资者演示与管理层对 AI 订单的原文",
    },
    "tsla": {
        "cover_eyebrow": "EV Platform Readout",
        "quarterly_label": "Delivery Layer",
        "historical_label": "Margin Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕交付节奏、单车盈利、能源业务与 FSD 叙事来读这一季。",
        "quarterly_lens": "交付、单车毛利与能源业务增长",
        "historical_lens": "汽车 / 储能 / 服务结构变化与利润波动",
        "evidence_lens": "股东 deck、财报稿与对 FSD / 产能的官方表述",
    },
    "berkshire": {
        "cover_eyebrow": "Capital Allocation Readout",
        "quarterly_label": "Capital Layer",
        "historical_label": "Compounding Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕保险承保、投资收益、经营现金流与资本配置来读这一季。",
        "quarterly_lens": "保险承保、投资收益与现金仓位",
        "historical_lens": "经营利润波动、资本回收与长期复利结构",
        "evidence_lens": "10-Q/10-K、股东信与 Buffett 口径",
    },
    "walmart": {
        "cover_eyebrow": "Retail Scale Readout",
        "quarterly_label": "Traffic Layer",
        "historical_label": "Format Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕同店、毛利、库存效率与电商渗透来读这一季。",
        "quarterly_lens": "同店、库存与电商利润率",
        "historical_lens": "美国/国际/Sam's Club 结构与效率变化",
        "evidence_lens": "财报稿、10-Q 与管理层对消费趋势的原文",
    },
    "lly": {
        "cover_eyebrow": "Therapy Franchise Readout",
        "quarterly_label": "Demand Layer",
        "historical_label": "Launch Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 GLP-1 放量、产能约束与核心产品组合迁移来读这一季。",
        "quarterly_lens": "核心药物放量、供给与价格兑现",
        "historical_lens": "新品接力与产品结构变化",
        "evidence_lens": "财报稿、产品说明与管理层对产能/需求的原文",
    },
    "jpm": {
        "cover_eyebrow": "Banking Franchise Readout",
        "quarterly_label": "Balance Sheet Layer",
        "historical_label": "Earnings Mix Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕净息差、投行交易、拨备与资本回报来读这一季。",
        "quarterly_lens": "净息差、市场业务与信用成本",
        "historical_lens": "收入结构、资本效率与盈利稳定性",
        "evidence_lens": "补充材料、财报稿与 Jamie Dimon 原文",
    },
    "xom": {
        "cover_eyebrow": "Energy Cash Machine Readout",
        "quarterly_label": "Commodity Layer",
        "historical_label": "Cycle Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕油价、炼化价差、产量与资本回报来读这一季。",
        "quarterly_lens": "油气价格、产量与炼化利润",
        "historical_lens": "上游/炼化/化工结构与现金回报能力",
        "evidence_lens": "财报稿、10-Q 与管理层对 commodity / capex 的表述",
    },
    "jnj": {
        "cover_eyebrow": "Healthcare Franchise Readout",
        "quarterly_label": "Portfolio Layer",
        "historical_label": "Resilience Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕药品增长、器械修复与组合抗波动能力来读这一季。",
        "quarterly_lens": "药品、器械与费用控制",
        "historical_lens": "组合韧性与长期利润质量",
        "evidence_lens": "财报稿、补充资料与产品线原文",
    },
    "visa": {
        "cover_eyebrow": "Payments Network Readout",
        "quarterly_label": "Volume Layer",
        "historical_label": "Network Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕支付量、跨境消费、费率与网络质量来读这一季。",
        "quarterly_lens": "支付量、跨境与费率稳定性",
        "historical_lens": "处理量、跨境 mix 与利润兑现",
        "evidence_lens": "财报稿与管理层对跨境/消费趋势的原文",
    },
    "asml": {
        "cover_eyebrow": "Lithography Readout",
        "quarterly_label": "Tool Layer",
        "historical_label": "Backlog Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 EUV/DUV 出货、订单、客户 capex 与长期路线图来读这一季。",
        "quarterly_lens": "系统出货、装机服务与订单能见度",
        "historical_lens": "系统/服务结构与 backlog 兑现路径",
        "evidence_lens": "results deck、新闻稿与管理层对客户 capex 的原文",
    },
    "micron": {
        "cover_eyebrow": "Memory Cycle Readout",
        "quarterly_label": "Pricing Layer",
        "historical_label": "Inventory Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 DRAM/NAND 定价、HBM 放量、库存与资本开支来读这一季。",
        "quarterly_lens": "定价、HBM 与库存去化",
        "historical_lens": "产品结构、周期位置与利润弹性",
        "evidence_lens": "earnings release、prepared remarks 与 HBM / pricing 原文",
    },
    "oracle": {
        "cover_eyebrow": "Enterprise Software Readout",
        "quarterly_label": "Cloud Transition Layer",
        "historical_label": "Recurring Revenue Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕 cloud migration、数据库维护收入与订单能见度来读这一季。",
        "quarterly_lens": "Cloud 转型、数据库业务与订单储备",
        "historical_lens": "Cloud / Software / Hardware 迁移与利润质量",
        "evidence_lens": "earnings release、10-Q 与管理层对 cloud backlog 的原文",
    },
    "costco": {
        "cover_eyebrow": "Membership Retail Readout",
        "quarterly_label": "Traffic Layer",
        "historical_label": "Loyalty Layer",
        "evidence_label": "Source Trail",
        "cover_tagline": "围绕会员费、同店、价格力与库存周转来读这一季。",
        "quarterly_lens": "会员费、同店与库存效率",
        "historical_lens": "净销售与会员费结构的长期复利",
        "evidence_lens": "财报稿、10-Q 与管理层对消费和 membership 的原文",
    },
}
REPORT_STYLE_VISUAL_UPDATES = {
    "nvidia": {"cover_rhythm": "dense", "section_divider": "beam"},
    "apple": {"cover_rhythm": "airy", "section_divider": "glass"},
    "alphabet": {"cover_rhythm": "playful", "section_divider": "spectrum"},
    "microsoft": {"cover_rhythm": "structured", "section_divider": "grid"},
    "amazon": {"cover_rhythm": "retail", "section_divider": "arc"},
    "tsmc": {"cover_rhythm": "precision", "section_divider": "ring"},
    "meta": {"cover_rhythm": "orbit", "section_divider": "orbit"},
    "avgo": {"cover_rhythm": "dense", "section_divider": "circuit"},
    "tsla": {"cover_rhythm": "velocity", "section_divider": "beam"},
    "berkshire": {"cover_rhythm": "ledger", "section_divider": "ledger"},
    "walmart": {"cover_rhythm": "retail", "section_divider": "arc"},
    "lly": {"cover_rhythm": "airy", "section_divider": "glass"},
    "jpm": {"cover_rhythm": "ledger", "section_divider": "ledger"},
    "xom": {"cover_rhythm": "industrial", "section_divider": "beam"},
    "jnj": {"cover_rhythm": "airy", "section_divider": "glass"},
    "visa": {"cover_rhythm": "ledger", "section_divider": "grid"},
    "asml": {"cover_rhythm": "precision", "section_divider": "grid"},
    "micron": {"cover_rhythm": "dense", "section_divider": "circuit"},
    "oracle": {"cover_rhythm": "structured", "section_divider": "beam"},
    "costco": {"cover_rhythm": "retail", "section_divider": "arc"},
}
for company_id, segment_colors in BRAND_SEGMENT_COLOR_UPDATES.items():
    COMPANY_REGISTRY[company_id]["brand"]["segment_colors"] = segment_colors
for company_id, theme_pattern in BRAND_THEME_PATTERN_UPDATES.items():
    COMPANY_REGISTRY[company_id]["brand"]["theme_pattern"] = theme_pattern
for company_id, alias_updates in SEGMENT_ALIAS_UPDATES.items():
    COMPANY_REGISTRY[company_id]["segment_aliases"].update(alias_updates)
for company_id, report_style in REPORT_STYLE_UPDATES.items():
    COMPANY_REGISTRY[company_id]["report_style"] = report_style
for company_id, report_visual_style in REPORT_STYLE_VISUAL_UPDATES.items():
    COMPANY_REGISTRY[company_id].setdefault("report_style", {}).update(report_visual_style)

COMPANY_REGISTRY["samsung"]["manual_sources_by_quarter"] = {
    "2025Q4": [
        {
            "label": "Samsung Electronics 4Q 2025 earnings materials",
            "url": "https://images.samsung.com/is/content/samsung/assets/global/ir/docs/2025_4Q_conference_eng.pdf",
            "kind": "official_release",
            "role": "earnings_release",
            "date": "2026-01-29",
        },
        {
            "label": "Samsung Electronics 4Q 2025 investor presentation",
            "url": "https://images.samsung.com/is/content/samsung/assets/global/ir/docs/2025_4Q_conference_eng.pdf",
            "kind": "presentation",
            "role": "earnings_presentation",
            "date": "2026-01-29",
        },
        {
            "label": "Samsung Electronics 4Q 2025 conference materials",
            "url": "https://images.samsung.com/is/content/samsung/assets/global/ir/docs/2025_4Q_conference_eng.pdf",
            "kind": "call_summary",
            "role": "earnings_call",
            "date": "2026-01-29",
        },
    ]
}


QUARTER_FIXTURES = {
    ("nvidia", "2025Q4"): {
        "fiscal_label": "Q4 FY2026",
        "release_date": "2026-02-25",
        "period_end": "2026-01-25",
        "coverage_months": ["2025-11", "2025-12", "2026-01"],
        "materials": ["earnings_release", "presentation", "call_summary"],
        "headline": "Blackwell 周期拉动收入与现金流继续上台阶，AI 基建支出仍在释放。",
        "takeaways": [
            "收入 681 亿美元，环比再增 20%，同比增长 73%，高基数下依然保持强劲加速。",
            "数据中心收入 623 亿美元，占总收入 91% 以上，结构继续向 AI 基础设施集中。",
            "GAAP 毛利率 75.0%，自由现金流 349 亿美元，利润兑现与现金创造同步强化。",
            "下一季度收入指引 780 亿美元，显示公司仍在消化更强的系统级与推理需求。",
        ],
        "latest_kpis": {
            "revenue_bn": 68.127,
            "revenue_yoy_pct": 73.0,
            "revenue_qoq_pct": 20.0,
            "gaap_gross_margin_pct": 75.0,
            "non_gaap_gross_margin_pct": 75.2,
            "operating_income_bn": 44.299,
            "net_income_bn": 42.960,
            "net_income_yoy_pct": 94.4,
            "operating_cash_flow_bn": 36.190,
            "free_cash_flow_bn": 34.902,
            "gaap_eps": 1.76,
            "non_gaap_eps": 1.62,
        },
        "guidance": {
            "mode": "official",
            "revenue_bn": 78.0,
            "comparison_revenue_bn": 68.127,
            "gaap_gross_margin_pct": 74.9,
            "comparison_margin_pct": 75.0,
            "current_label": "本季收入",
            "comparison_label": "下一季收入指引",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "下一季毛利率指引",
            "commentary": "公司下一季度指引继续上修，但明确指出中国数据中心计算收入未被纳入展望。",
        },
        "current_segments": [
            {"name": "Data Center", "value_bn": 62.314},
            {"name": "Gaming", "value_bn": 3.727},
            {"name": "Professional Visualization", "value_bn": 1.321},
            {"name": "Automotive", "value_bn": 0.604},
            {"name": "OEM and Other", "value_bn": 0.161},
        ],
        "income_statement": {
            "subtitle": "利润表页补入 NVIDIA 官方成本与费用科目，突出高毛利与费用投向的组合关系。",
            "revenue_bn": 68.127,
            "gross_profit_bn": 51.093,
            "cost_of_revenue_bn": 17.034,
            "gross_margin_pct": 75.0,
            "operating_profit_bn": 44.299,
            "operating_expenses_bn": 6.794,
            "net_profit_bn": 42.960,
            "net_margin_pct": 63.1,
            "opex_breakdown": [
                {"name": "Research and development", "value_bn": 4.680, "pct_of_revenue": 6.9, "color": "#E11D48"},
                {"name": "Selling, general and administrative", "value_bn": 2.114, "pct_of_revenue": 3.1, "color": "#F43F5E"},
            ],
            "below_operating_items": [
                {"name": "Taxes & other", "value_bn": 1.339, "color": "#D92D20"},
            ],
        },
        "management_themes": [
            {"label": "Blackwell 量产与系统级交付", "score": 96, "note": "从芯片走向整机与机柜交付，单客户价值量继续提升。"},
            {"label": "推理需求成为第二增长曲线", "score": 90, "note": "推理侧 token 成本下降后，客户部署节奏明显加快。"},
            {"label": "网络与平台软件 attach rate", "score": 76, "note": "网络、互连和软件栈继续抬高单集群收入密度。"},
            {"label": "中国收入不计入展望", "score": 58, "note": "管理层仍把地缘与出口限制视为中期不确定因素。"},
        ],
        "qna_themes": [
            {"label": "Blackwell 供给与良率", "score": 84, "note": "市场更关心供给爬坡速度，而非单纯需求可见度。"},
            {"label": "Inference economics", "score": 80, "note": "单位 token 成本下降后，推理部署强度上升。"},
            {"label": "客户预算持续性", "score": 67, "note": "云厂商和企业客户仍在拉长资本开支周期。"},
            {"label": "中国敞口与替代影响", "score": 49, "note": "管理层在口径上保持谨慎，没有把该部分收入计入指引。"},
        ],
        "risks": [
            {"label": "出口限制反复", "score": 66, "note": "区域性限制可能扰动订单结构与指引兑现。"},
            {"label": "供给链复杂度上升", "score": 52, "note": "系统交付扩张后，对封装、互连、整机协同要求更高。"},
            {"label": "客户资本开支正常化", "score": 45, "note": "极高增速之后，比较基数与投资回报压力会逐步抬升。"},
        ],
        "catalysts": [
            {"label": "Blackwell 平台全面放量", "score": 95, "note": "若机柜级交付加速，收入弹性仍有上修空间。"},
            {"label": "推理集群持续扩容", "score": 82, "note": "推理需求将进一步提升 GPU、网络和软件附加值。"},
            {"label": "企业 AI 渗透深化", "score": 68, "note": "企业侧负载从试点转向生产化会拉长成长周期。"},
        ],
        "evidence_cards": [
            {
                "title": "收入披露",
                "text": "官方新闻稿披露第四季度收入 681 亿美元，环比增 20%，同比增 73%。",
                "source_label": "NVIDIA earnings release",
            },
            {
                "title": "数据中心披露",
                "text": "官方材料披露数据中心收入 623 亿美元，同比增长 75%，仍是绝对核心驱动。",
                "source_label": "NVIDIA earnings release",
            },
            {
                "title": "展望口径",
                "text": "下一季度收入指引 780 亿美元，并明确未假设来自中国的数据中心计算收入。",
                "source_label": "NVIDIA earnings release",
            },
        ],
        "coverage_notes": [
            "当前样本已内置官方财报新闻稿与展示材料摘要，未内置完整电话会全文。",
            "若补充 transcript 上传，系统会以手工材料替换当前电话会摘要模块。",
        ],
        "sources": [
            {
                "label": "NVIDIA Q4 FY2026 earnings release",
                "url": "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-fourth-quarter-and-fiscal-2026",
                "kind": "official_release",
                "date": "2026-02-25",
            },
            {
                "label": "NVIDIA FY2026 Form 10-K",
                "url": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm",
                "kind": "sec_filing",
                "date": "2026-02-25",
            },
        ],
    },
    ("avgo", "2025Q4"): {
        "fiscal_label": "Q1 FY2026",
        "release_date": "2026-03-05",
        "period_end": "2026-02-01",
        "coverage_months": ["2025-11", "2025-12", "2026-01"],
        "materials": ["earnings_release", "call_summary"],
        "headline": "AI 半导体与软件平台共同支撑收入扩张，但历史分部季度披露仍不足。",
        "takeaways": [
            "收入 149 亿美元，同比增长 25%，AI 相关收入仍是最强增量来源。",
            "AI semiconductor revenue 为 41 亿美元，管理层给出下一季度约 44 亿美元展望。",
            "自由现金流 60 亿美元，现金流率维持高位，软件业务继续稳定利润结构。",
            "由于缺少完整的 12 季季度分部披露，历史结构页将自动降级为总量与盈利质量分析。",
        ],
        "latest_kpis": {
            "revenue_bn": 14.916,
            "revenue_yoy_pct": 25.0,
            "revenue_qoq_pct": 6.1,
            "gaap_gross_margin_pct": 78.1,
            "non_gaap_gross_margin_pct": 79.1,
            "operating_income_bn": 8.741,
            "net_income_bn": 5.503,
            "operating_cash_flow_bn": 6.100,
            "free_cash_flow_bn": 6.000,
            "gaap_eps": 1.14,
            "non_gaap_eps": 1.60,
        },
        "guidance": {
            "mode": "official",
            "revenue_bn": 15.8,
            "comparison_revenue_bn": 14.916,
            "gaap_gross_margin_pct": 66.0,
            "comparison_margin_pct": 78.1,
            "current_label": "本季收入",
            "comparison_label": "下一季收入指引",
            "current_margin_label": "本季毛利率",
            "comparison_margin_label": "利润率参考",
            "commentary": "下一季度指引继续体现 AI 半导体拉动，但利润率口径更偏稳健而非激进上修。",
        },
        "current_segments": [
            {"name": "Semiconductor Solutions", "value_bn": 8.212},
            {"name": "Infrastructure Software", "value_bn": 6.704},
        ],
        "management_themes": [
            {"label": "AI 半导体持续扩容", "score": 94, "note": "AI networking 与 accelerator 相关需求仍是最强驱动。"},
            {"label": "软件平台稳定利润", "score": 78, "note": "VMware 与基础设施软件收入维持高利润率和韧性。"},
            {"label": "组合式经营杠杆", "score": 72, "note": "硬件增长与软件现金流的组合仍然有效。"},
            {"label": "下一季 AI 指引延续", "score": 70, "note": "管理层对 AI 半导体收入给出进一步增长预期。"},
        ],
        "qna_themes": [
            {"label": "AI 网络与定制芯片", "score": 82, "note": "市场关注非 GPU 侧的 AI 连接与定制机会。"},
            {"label": "软件整合进度", "score": 61, "note": "重点在协同效率而不是单纯收入规模。"},
            {"label": "利润率可持续性", "score": 55, "note": "组合利润率维持高位，但进一步扩张空间有限。"},
        ],
        "risks": [
            {"label": "季度分部数据连续性不足", "score": 72, "note": "历史结构分析需降级展示，影响可比性。"},
            {"label": "AI 需求集中度较高", "score": 58, "note": "增量客户集中时，订单波动会更快反映到季度节奏。"},
            {"label": "软件整合执行风险", "score": 44, "note": "整合节奏若放缓，会拖累利润率提升。"},
        ],
        "catalysts": [
            {"label": "AI 半导体收入继续上修", "score": 90, "note": "若 AI networking 与定制芯片扩张，收入上修概率较高。"},
            {"label": "软件协同兑现", "score": 68, "note": "VMware 平台渗透深化可提升经常性收入质量。"},
            {"label": "资本回报延续", "score": 55, "note": "高自由现金流有助于维持估值韧性。"},
        ],
        "evidence_cards": [
            {
                "title": "AI revenue 披露",
                "text": "管理层披露本季度 AI revenue 为 41 亿美元，并指引下一季度 AI 半导体收入约 44 亿美元。",
                "source_label": "Broadcom earnings release",
            },
            {
                "title": "软件业务稳定器",
                "text": "基础设施软件收入 67 亿美元，为利润率和现金流提供稳定底盘。",
                "source_label": "Broadcom earnings release",
            },
            {
                "title": "结构限制说明",
                "text": "当前样本缺少完整季度分部历史，因此 12 季结构分析自动降级为总量与盈利质量视角。",
                "source_label": "System coverage note",
            },
        ],
        "coverage_notes": [
            "当前样本未内置完整电话会 transcript，电话会页基于官方披露摘要与管理层主题卡片生成。",
            "由于缺少连续 12 季季度分部披露，结构迁移页将使用降级版式。 ",
        ],
        "sources": [
            {
                "label": "Broadcom Q1 FY2026 earnings release",
                "url": "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-first-quarter-fiscal-year-2026-financial",
                "kind": "official_release",
                "date": "2026-03-05",
            },
            {
                "label": "Broadcom Q4 FY2025 earnings release",
                "url": "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-fourth-quarter-and-fiscal-year-2025",
                "kind": "official_release",
                "date": "2025-12-04",
            },
        ],
    },
    **OFFICIAL_MAG7_FIXTURES,
}
